### PR TITLE
Use the organization action for linting

### PR DESCRIPTION
**Pull request by JackWilb**
### Does this PR close any open issues?
Nope, it's just an improvement to help us reduce redundant code across the repos.

### Give a longer description of what this PR addresses and why it's needed
I've added an action in multinet-app/.github that handles this logic. The gameplan is to prefer using that to workflow files in each individual repo to provide more consistent testing logic.

### Provide pictures/videos of the behavior before and after these changes (optional)
N/A

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [x] Make sure it works
- [x] Change the branch protection rules to make it use the new new for the workflow

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
I'm confused by this. Why place the action in a separate repo?

**Comment by JackWilb** [comment]
> I'm confused by this. Why place the action in a separate repo?

It allows us to reduce redundant actions across the repos. Instead, it's now in one central place and can be reused. I'm also using it for PR templates on all our repos

**Comment by AlmightyYakob** [comment]
> It allows us to reduce redundant actions across the repos. Instead, it's now in one central place and can be reused. I'm also using it for PR templates on all our repos

I see, I was slightly confused. I think this is fine, although one thing I'll say is I don't think the app registry step should live in that lint action, since it only applies to this repo. Can't that step just be placed here, before the use of that action?

**Comment by JackWilb** [comment]
> I see, I was slightly confused. I think this is fine, although one thing I'll say is I don't think the app registry step should live in that lint action, since it only applies to this repo. Can't that step just be placed here, before the use of that action?

That's not possible because the checkout and yarn steps all happen in the other action. If we wanted that, we'd have to do the checkout here, and then the `yarn init-appregistry`. I think it's okay to just pass through a variable that triggers it if it needs it, since it's just a one off. If that changes, we can update it pretty easily

**Pull request merged**
