### PR TITLE
Permissions ui

### LINKED ISSUE #82: Add UI for user permissions settings

### PR DESCRIPTION
**Pull request by jtomeck**
Created the menu and modal based on the permissions mockup. I believe this is ready for @AlmightyYakob to start tying in the functionality?

Closes #82 
Depends on https://github.com/multinet-app/multinetjs/pull/15
Depends on https://github.com/multinet-app/multinet-server/pull/430

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
We'll probably want to pull this menu item out into it's own component, for both organization as well as to accommodate for #106, as I was planning on placing the button for the AQL dialog in that menu. If it's okay with you @jtomeck I can try pulling this out into it's own component, so that I can rebase my branch for #106 off of this one, while we wait for backend functionality.

**Comment by AlmightyYakob** [comment]
@jtomeck I've factored out the new dialog into it's own component, and it seems to behave the same as before. Maybe you could verify this as well.

**Comment by waxlamp** [comment]
This is looking good. Some specific thoughts:
- The v-switch being used for whether the workspace is public doesn't seem clear enough. I think it's a classic problem of v-switch usage. I wonder if replacing it with a checkbox, and changing the lock icon for the word `Public` would be helpful. Thoughts, @jtomeck?
- We need a mechanism for removing someone's permissions altogether--this would naturally be something like an X that we could click to remove a name from the list.
- The "owner" role can't be easily changed to a different role the same way other roles can be granted and managed. That is, the owner of a workspace is a special position, and should maybe be indicated as such.
  - A bit more follow-up detail: ownership can only by changed by initiating a "transfer" operation (similar to how it's done on GitHub, with flashing red warning lights and a confirmation dialog), and I believe this would need to be a special dialog that's separated from this more ordinary level of permissions management.

**Comment by jtomeck** [comment]
Sorry for taking a while to get back into this PR. I will be taking a look tomorrow first thing in the morning and will leave a review on everything that's been done so far!

**Comment by AlmightyYakob** [comment]
> Sorry for taking a while to get back into this PR. I will be taking a look tomorrow first thing in the morning and will leave a review on everything that's been done so far!

FYI what I've just pushed won't allow for deploy previews until https://github.com/multinet-app/multinetjs/pull/15 is updated, and the version in the client is bumped.

**Comment by waxlamp** [comment]
> > Sorry for taking a while to get back into this PR. I will be taking a look tomorrow first thing in the morning and will leave a review on everything that's been done so far!
> 
> FYI what I've just pushed won't allow for deploy previews until [multinet-app/multinetjs#15](https://github.com/multinet-app/multinetjs/pull/15) is updated, and the version in the client is bumped.

@jtomeck, I can help you set up your local build to work properly--just let me know when you're working on it and I'll try to get some time to help you out (or @AlmightyYakob can do it as well).

**Comment by jtomeck** [comment]
@waxlamp 

> * The v-switch being used for whether the workspace is public doesn't seem clear enough.

I don't see why this isn't clear. Can you elaborate a bit on your concerns here?

> * We need a mechanism for removing someone's permissions altogether

I agree, I think the "X" icon could go on either side of the list item. Thoughts?

> * The "owner" role can't be easily changed to a different role the same way other roles can be granted and managed.

This makes sense. Where do you think this transfer is initiated. I think from how I'm interpreting your explanation, it could be a button in the bottom of the modal for owners that says "transfer ownership." This could take them through a separate UI process based on your comments. What do you think?

**Comment by AlmightyYakob** [comment]
> > * We need a mechanism for removing someone's permissions altogether
> 
> I agree, I think the "X" icon could go on either side of the list item. Thoughts?

Just to note, I've actually already added this and it seems to look/feel right.


> > * The "owner" role can't be easily changed to a different role the same way other roles can be granted and managed.
> 
> This makes sense. Where do you think this transfer is initiated. I think from how I'm interpreting your explanation, it could be a button in the bottom of the modal for owners that says "transfer ownership." This could take them through a separate UI process based on your comments. What do you think?

Just another aside; While I do think the ownership transfer should go in this UI, I think it might be better to do that as a follow up PR, since it may add a decent amount of complexity.

**Comment by jtomeck** [comment]
> Just to note, I've actually already added this and it seems to look/feel right.

Yeah I was having some build issues and wasn't seeing that. It's sorted out now and I think it's perfect.

**Comment by waxlamp** [comment]
> > > * We need a mechanism for removing someone's permissions altogether
> > 
> > 
> > I agree, I think the "X" icon could go on either side of the list item. Thoughts?
> 
> Just to note, I've actually already added this and it seems to look/feel right.
> 

Agreed :+1: 

I just helped Jared get his local build working so he should be able to see this and weigh in as well.

> > > * The "owner" role can't be easily changed to a different role the same way other roles can be granted and managed.
> > 
> > 
> > This makes sense. Where do you think this transfer is initiated. I think from how I'm interpreting your explanation, it could be a button in the bottom of the modal for owners that says "transfer ownership." This could take them through a separate UI process based on your comments. What do you think?
> 
> Just another aside; While I do think the ownership transfer should go in this UI, I think it might be better to do that as a follow up PR, since it may add a decent amount of complexity.

Also agree. I opened #116 to track it.

**Comment by waxlamp** [comment]
One piece of feedback that I mentioned to @jtomeck in a meeting, but recording here for everyone else: the v-switch with the lock icon just feels wrong to me: workspaces are, by default, "private" and they can be made public by taking an action. Therefore, I think the option should be controlled by a checkbox, and rather than an icon that indicates whether it's "locked" or not (which is the wrong metaphor), I'd like for the checkbox to have an explicit description on it, something along the lines of `Make this workspace public`, possibly with a hoverable question mark that further explains what that means (that all users, including ones who are not logged in, will be able to view the workspace and run queries on it). This checkbox should also go above the part of the UI that lists users and their permissions (or, just below that part), since it is really a type of permission grant, rather than some special property of the workspace.

**Comment by jtomeck** [comment]
@waxlamp 

> This checkbox should also go above the part of the UI that lists users and their permissions (or, just below that part), since it is really a type of permission grant, rather than some special property of the workspace.

I vote for below. Is this something you want me to take care of on this PR, or do you just want my review on things for now and a discussion on future plans?

**Comment by AlmightyYakob** [comment]
> I vote for below. Is this something you want me to take care of on this PR, or do you just want my review on things for now and a discussion on future plans?

Discussed offline, I'll make this change.

**Comment by AlmightyYakob** [comment]
> This checkbox should also go above the part of the UI that lists users and their permissions (or, just below that part), since it is really a type of permission grant, rather than some special property of the workspace.

Above:

Screenshot from 2020-08-04 14-05-14

Below:

Screenshot from 2020-08-04 14-04-37

I personally think above looks better, what do you guys think?

**Comment by jtomeck** [comment]
> I personally think above looks better, what do you guys think?

@AlmightyYakob personally I think it gets a bit lost above. What I was thinking when I said below was pairing it with the action buttons on the left side of the modal's footer.

**Comment by JackWilb** [comment]
I prefer below, too

**Comment by AlmightyYakob** [comment]
@jtomeck how's this look 
Screenshot from 2020-08-05 11-45-12

**Comment by jtomeck** [comment]
Looks great! Precisely what I was envisioning :)

**Comment by JackWilb** [comment]
@AlmightyYakob I'm unable to access the permissions for workspaces that I own at the moment, even ones that I've just made. Is there some issue with the permissions logic for viewing the modal?

**Comment by waxlamp** [comment]
@AlmightyYakob can you change the text on the checkbox to `Make this workspace public`?

How hard is it to add a small question mark icon after that text that on hover opens a popover that explains what "public" means?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob can you change the text on the checkbox to `Make this workspace public`?
> 
> How hard is it to add a small question mark icon after that text that on hover opens a popover that explains what "public" means?

Not hard, but what would you want the tooltip to say?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob I'm unable to access the permissions for workspaces that I own at the moment, even ones that I've just made. Is there some issue with the permissions logic for viewing the modal?

I have no issue locally, are you running this locally? And are you logged in?

**Comment by waxlamp** [comment]
> @AlmightyYakob I'm unable to access the permissions for workspaces that I own at the moment, even ones that I've just made. Is there some issue with the permissions logic for viewing the modal?

You need to make sure you have all three of the following set up locally:
- this branch of multinet-client
- the `workspace-permission-endpoints` branch of multinet-server
- the `workspace-permissions` branch of multinetjs
  - this also needs to be `yarn link`ed into multinet-client

Regarding multinetjs, we *just* published 0.16.0 which includes the `workspace-permissions` branch, so you can probably just update your multinet-client package.json multinet version and re-run `yarn install`.

**Comment by waxlamp** [comment]
> > @AlmightyYakob can you change the text on the checkbox to `Make this workspace public`?
> > How hard is it to add a small question mark icon after that text that on hover opens a popover that explains what "public" means?
> 
> Not hard, but what would you want the tooltip to say?

`Public workspaces are readable by all users, even those who are not logged in. You can revoke this at any time by unchecking the box.`

**Comment by JackWilb** [comment]
> > @AlmightyYakob I'm unable to access the permissions for workspaces that I own at the moment, even ones that I've just made. Is there some issue with the permissions logic for viewing the modal?
> 
> I have no issue locally, are you running this locally? And are you logged in?

No, I'm using the deploy preview and I'm logged in

**Comment by jtomeck** [comment]
> > > @AlmightyYakob can you change the text on the checkbox to `Make this workspace public`?
> > > How hard is it to add a small question mark icon after that text that on hover opens a popover that explains what "public" means?
> > 
> > 
> > Not hard, but what would you want the tooltip to say?
> 
> `Public workspaces are readable by all users, even those who are not logged in. You can revoke this at any time by unchecking the box.`

This is kind of a long tooltip. I'd recommend removing the second sentence.

**Comment by waxlamp** [comment]
> > > > @AlmightyYakob can you change the text on the checkbox to `Make this workspace public`?
> > > > How hard is it to add a small question mark icon after that text that on hover opens a popover that explains what "public" means?
> > > 
> > > 
> > > Not hard, but what would you want the tooltip to say?
> > 
> > 
> > `Public workspaces are readable by all users, even those who are not logged in. You can revoke this at any time by unchecking the box.`
> 
> This is kind of a long tooltip. I'd recommend removing the second sentence.

I'm ok with that, but I don't want this in a tooltip, I want it in a popover. Sometimes you see these in the wild appearing on terms with a dotted gray underline, and the popover generally means a slightly longer message is tolerable. I wish I had an example I could point you to off the top of my head :confused:

**Comment by jtomeck** [comment]
> I'm ok with that, but I don't want this in a tooltip, I want it in a popover. Sometimes you see these in the wild appearing on terms with a dotted gray underline, and the popover generally means a slightly longer message is tolerable. I wish I had an example I could point you to off the top of my head 😕

Yeah I'm cool with doing that. If you want to keep the second sentence it's not hurting anything. I just think it's a little extra and want to make sure it's not making anything too busy, since it's explaining obvious functionality of the checkbox, imo.

**Comment by waxlamp** [comment]
> > I'm ok with that, but I don't want this in a tooltip, I want it in a popover. Sometimes you see these in the wild appearing on terms with a dotted gray underline, and the popover generally means a slightly longer message is tolerable. I wish I had an example I could point you to off the top of my head confused
> 
> Yeah I'm cool with doing that. If you want to keep the second sentence it's not hurting anything. I just think it's a little extra and want to make sure it's not making anything too busy, since it's explaining obvious functionality of the checkbox, imo.

My goal with that second sentence is to reassure the user that they're not doing anything irrevocable (to strengthen the fact that it's a checkbox). Because it's a matter of turning what was private into something that is very public, the extra hand-holding is worthwhile IMO.

**Comment by AlmightyYakob** [comment]
Thoughts? @waxlamp @jtomeck 
Screenshot from 2020-08-06 12-13-02

**Comment by waxlamp** [comment]
I like it :smile:

**Comment by jtomeck** [comment]
I like it as well. Nice work!

**Pull request merged**
