### PR TITLE
Main page updates

### PR DESCRIPTION
**Pull request by JackWilb**
### Does this PR close any open issues?
No. These are requests from Alex

### Give a longer description of what this PR addresses and why it's needed
I updated the html title attribute to the one Alex requested. I also moved the logos to a new footer and made them grayscale.

### Provide pictures/videos of the behavior before and after these changes (optional)
Old:
image

New:
image

### Are there any additional TODOs before this PR is ready to go?
No

### CODE REVIEW

**Comment by alexsb** [comment]
Thanks, great start. 

* For the logo bar, I notice that VDL doesn't use a transparent background logo. 
* For the intro, I was thinking more about something like in Ordino: 
image

A good screenshot could be nice!

Tag line could be: 

Multinet is visualization tool for networks with attributes associated with the nodes and links. 

Here's the basic idea: 

image


https://www.figma.com/file/TO4NZ4UdMr13hpQsBGlp7I/Multinet-Front-Page?node-id=0%3A1

This isn't perfect, I didn't dive too deep into the prototype (font sizes, font types, etc), but should give you an idea. 

Also note the distinction between "Your Workspaces" and "Public Workspaces".

**Comment by JackWilb** [comment]
There's still work to be done here. The footer overlaps with the network detail, and likely other view. I also need to do some testing with larger lists of networks, tables, workspaces, etc. to make sure that the overflows work as intended

**Comment by JackWilb** [comment]
> There's still work to be done here. The footer overlaps with the network detail, and likely other view. I also need to do some testing with larger lists of networks, tables, workspaces, etc. to make sure that the overflows work as intended

Done

**Comment by alexsb** [comment]
This is progress, and it's correct as far as the technical specs go, but it doesn't yet look good. It looks better on a narrow screen than on a wide screen: 

image

vs

image
 


 Here are some aesthetic things you can try: 

* Unify the fonts; it seems a bit all over the place in terms of style and size. 
* The "heading" at the top should be taller than the "getting started". 
* Try adding the mltinet logo. 
* Try making the icons larger
* Especially the game icon is wider and looks like it could use more padding on the right. 
* Replace the teaser with something taller that looks good. 
* Give the "example cards" a maximum width, instead of stretching them out on a wide screen.
* Add a link to the "Sign up" that pops up the sign up dialog. 
* Hide the "Your Workspaces" when not logged in.
* Add "or explore the public workspaces" to the "Try a demo below"
* Change the "Sign up" and "Try" sentences to sentence case (lower case except for the first word) 
* The "New Workspace" button doesn't do anything when not logged in. It should probably be hidden. 
* We could also add a third option: "Lear more about Multinet" that links to an about page. I can add the text if you can set that up. 
   

Wrt design: you could also talk to Nathan https://sci.utah.edu/people/nathang.html if he can make suggestions. I've never tried it, but I think that's supposed to be part of his duties.

**Comment by JackWilb** [comment]
Tracking those TODOs here:

- [ ] Unify the fonts; it seems a bit all over the place in terms of style and size. 
- [ ] The "heading" at the top should be taller than the "getting started". 
- [ ] Try adding the multinet logo. 
- [x] Try making the icons larger
- [x] Especially the game icon is wider and looks like it could use more padding on the right. 
- [ ] Replace the teaser with something taller that looks good. 
- [ ] Give the "example cards" a maximum width, instead of stretching them out on a wide screen.
- [ ] Add a link to the "Sign up" that pops up the sign up dialog. 
- [ ] Hide the "Your Workspaces" when not logged in.
- [x] Add "or explore the public workspaces" to the "Try a demo below"
- [x] Change the "Sign up" and "Try" sentences to sentence case (lower case except for the first word) 
- [x] The "New Workspace" button doesn't do anything when not logged in. It should probably be hidden. 
- [ ] We could also add a third option: "Learn more about Multinet" that links to an about page. I can add the text if you can set that up.

**Comment by JackWilb** [comment]
Request from Alex to remove the sidebar from the teaser and then it should be good to go

**Pull request merged**
